version: '3.8'
services:
  #docker compose --env-file=.env.docker up -d 

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/nginx.Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    volumes:
      - ${WWW_ROOT_FOLDER}:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
